FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

# Set working directory
WORKDIR '/usr/src/magmacore'

# Install required system packages
RUN apt-get update --fix-missing && \
    apt-get install -y wget bzip2 ca-certificates curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Miniconda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -a && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

# Set environment variables
ENV PATH /opt/conda/bin:$PATH

# Copy conda environment file
COPY envs/conda/environment.yml .

# Copy requirements file
COPY envs/pip/requirements_GH.txt .

# Create environment from yaml file
RUN conda env create -f environment.yml && conda clean -afy

# Set up bash to run with luxai_s2 conda environment
SHELL ["conda", "run", "-n", "luxai_s2", "/bin/bash", "-c"]

# Set PATH for the Conda environment
ENV PATH /opt/conda/envs/luxai_s2/bin:$PATH

RUN pip install --no-cache-dir --upgrade pip

# Install basic dev tools, like GCC
RUN apt update -y && apt upgrade -y && apt install -y build-essential && apt-get install -y manpages-dev

# Install vec_noise
RUN pip install numpy==1.26.4 wheel==0.42.0 setuptools==69.0.3 protobuf==4.24.0 vec_noise

# Install requirements
RUN pip install --no-cache-dir -r requirements_GH.txt

# Add Lux conda env to ipykernel to run Notebooks
RUN python -m ipykernel install --user --name=luxai_s2 --display-name "LuxAI S2"

# Install Jax with Lux

RUN pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

# Switch back to bash
SHELL ["/bin/bash","-c"]

# Initialize conda
RUN conda init

# Activate luxai_s2 environment on bash startup
RUN echo 'conda activate luxai_s2' >> ~/.bashrc

